blank_issues_enabled: true
contact_links:
  - name: ETALEE Support
    url: https://t.me/ET_ALI
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://Yukki.tech/
    about: Documentation for getting started with bot.
